import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#061237",
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 130,
    marginBottom: 25,
    width: "90%",
  },
  headerText: {
    color: "white",
    fontSize: 45,
    fontWeight: "700",
    marginRight: 10,
  },
  logo: { width: 55, height: 55 },

  mainTabContainer: {
    width: "90%",
    backgroundColor: "#0d1c42",
    borderRadius: 50,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  mainTab: {
    flex: 1,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
  },
  activeMainTab: { backgroundColor: "#256DFF" },
  mainTabText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 17,
    fontWeight: "500",
  },
  activeMainText: { color: "white" },

  subTabInsideBox: {
    width: "100%",
    backgroundColor: "#0d1c42",
    borderRadius: 40,
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  subTabSmall: {
    flex: 1,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 40,
  },
  activeSubTab: { backgroundColor: "#256DFF" },
  subText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 16,
    fontWeight: "500",
  },
  activeSubText: { color: "white" },

  keyboardContainer: { width: "100%", alignItems: "center" },
  tripInfoWrapper: { width: "90%", alignSelf: "center" },
  tripInfo: {
    width: "100%",
    borderRadius: 20,
    backgroundColor: "rgb(7,18,54)",
    padding: 18,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 15,
    marginTop: 5,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  icon: {
    width: 22,
    height: 22,
    tintColor: "rgba(255,255,255,0.5)",
    marginRight: 10,
  },
  textInput: {
    flex: 1,
    height: 45,
    fontSize: 16,
    borderBottomWidth: 0.2,
    borderColor: "rgba(255,255,255,0.15)",
    color: "white",
  },
  dropdown: {
    position: "absolute",
    backgroundColor: "#061237",
    borderRadius: 10,
    top: 50,
    left: 55,
    right: 40,
    zIndex: 9999,
    maxHeight: 160,
    width: "75%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  dropdownText: {
    color: "white",
    fontSize: 14,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomColor: "rgba(255,255,255,0.1)",
    borderBottomWidth: 1,
  },
  dateAndSeatsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  dateAndIcon: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  smallInput: {
    flex: 1,
    height: 45,
    fontSize: 16,
    borderBottomWidth: 0.2,
    borderColor: "rgba(255,255,255,0.15)",
    color: "white",
  },
  descriptionTextInput: {
    width: "100%",
    height: 95,
    fontSize: 16,
    color: "white",
    borderBottomWidth: 0.2,
    borderColor: "rgba(255,255,255,0.15)",
    justifyContent: "flex-start",
    textAlignVertical: "top",
  },

  photoContainer: {
    width: "90%",
    backgroundColor: "rgb(7,18,54)",
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadBox: {
    width: "100%",
    height: 140,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  uploadIcon: {
    width: 45,
    height: 45,
    tintColor: "rgba(255,255,255,0.7)",
    marginBottom: 8,
  },
  uploadText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 17,
    fontWeight: "500",
  },
  uploadHint: { color: "rgba(255,255,255,0.5)", fontSize: 13, marginTop: 4 },

  textInputPhoto: {
    width: "100%",
    height: 45,
    fontSize: 16,
    color: "white",
    borderBottomWidth: 0.2,
    borderColor: "rgba(255,255,255,0.15)",
    marginBottom: 15,
  },
  descriptionPhotoInput: {
    width: "100%",
    height: 95,
    fontSize: 16,
    color: "white",
    borderBottomWidth: 0.2,
    borderColor: "rgba(255,255,255,0.15)",
    justifyContent: "flex-start",
    textAlignVertical: "top",
  },

  postButton: {
    backgroundColor: "#256DFF",
    width: "90%",
    height: 50,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    shadowColor: "#256DFF",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    alignSelf: "center",
  },
  buttonText: { color: "white", fontSize: 19, fontWeight: "600" },
});
